name: Publish docs on permaweb

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run docs:build
      - run: npx permaweb-deploy --ant-process ${{ env.ANT_PROCESS }} --deploy-folder ./docs/docs/dist
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ANT_PROCESS: "4eMZpmmAGu05o2eW1yPHqIrVYAUbqEpLoAJ0V3F10-o"
